{
 "title": "Microservices Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "container", "query": "label_values(container)" },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({container=~\"$container\"} |= `` [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Recent Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "{container=~\"$container\", container!~\"(.*loki.*|.*promtail.*|.*grafana.*)\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=~\"$container\"} |= \"$search\""
    }
   ]
  }
 ]
}