basePath: /
definitions:
  handler.errorResp:
    properties:
      error:
        type: string
    type: object
  handler.loginReq:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  handler.loginResp:
    properties:
      email:
        type: string
      id:
        type: integer
      token:
        type: string
      username:
        type: string
    type: object
  handler.registerReq:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  handler.registerResp:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8084
info:
  contact: {}
  description: Authentication service (register / login / token)
  title: Auth Service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.loginResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResp'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.errorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResp'
      summary: Login with email or username
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.registerReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.registerResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResp'
      summary: Register a new user
      tags:
      - Auth
swagger: "2.0"
